import logging
from typing import Dict, List, Any

from src.config import Document, VerifiedAnswer, Citation
from src.llm import chat_json

logger = logging.getLogger(__name__)

class Verifier:
    """Verifies draft answers against provided documents."""

    def verify(
        self,
        query: str,
        draft_answer: str,
        documents: List[Document],
        cited_clauses: List[str],
        is_follow_up: bool = False,
    ) -> VerifiedAnswer:
        """
        Verifies all claims in a draft answer.

        Args:
            query: Original user query.
            draft_answer: Draft text generated by specialist(s).
            documents: Available context documents.
            cited_clauses: Clauses cited by the specialist(s).
            is_follow_up: Whether this is a follow-up question in a conversation.

        Returns:
            A VerifiedAnswer object.
        """
        docs_context = "\n".join([f"Clause {d.metadata.get('clause_id', 'unknown')}: {d.content}" for d in documents])

        follow_up_note = ""
        if is_follow_up:
            follow_up_note = (
                "\n\nIMPORTANT: This answer is part of a multi-turn conversation. "
                "The draft may reference or summarize information from a previous answer that was already verified. "
                "Do NOT penalize the confidence score for reusing previously verified information. "
                "Only flag claims that introduce NEW facts not found in the documents."
            )

        system_prompt = (
            "You are a verifier agent. Check EVERY claim in the draft answer against the provided documents. "
            "For each claim, find supporting text or flag it as unsupported. "
            "Assign a confidence score (0.0 to 1.0) based on evidence strength. "
            "If confidence < 0.4, set should_abstain=True and provide a reason. "
            "Strip any claims not supported by the documents from the verified answer. "
            "Return JSON with keys: 'verified_answer' (str), 'confidence' (float), 'should_abstain' (bool), "
            "'abstention_reason' (str or null), and 'verified_clauses' (List[str])."
            + follow_up_note
        )
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Draft Answer:\n{draft_answer}\n\nDocuments:\n{docs_context}\n\nQuery: {query}"}
        ]

        res = chat_json(messages)
        if "error" in res:
            logger.warning(f"Verifier unavailable, using draft answer: {res['error']}")
            # Fall back to the specialist's draft — still useful to the user
            fallback_citations = self._build_citations(cited_clauses, documents)
            return VerifiedAnswer(
                answer=draft_answer,
                citations=fallback_citations,
                confidence=0.7,
                should_abstain=False,
                abstention_reason=""
            )

        confidence = float(res.get("confidence", 0.0))
        should_abstain = bool(res.get("should_abstain", False))
        if confidence < 0.4:
            should_abstain = True

        verified_answer = res.get("verified_answer", draft_answer)
        verified_clauses = res.get("verified_clauses", cited_clauses)

        citations = self._build_citations(verified_clauses, documents)

        return VerifiedAnswer(
            answer=verified_answer,
            citations=citations,
            confidence=confidence,
            should_abstain=should_abstain,
            abstention_reason=res.get("abstention_reason", "")
        )

    def _build_citations(self, verified_clauses: List[str], documents: List[Document]) -> List[Citation]:
        """Build Citation objects for verified claims."""
        citations = []
        for clause in verified_clauses:
            for doc in documents:
                if doc.metadata.get("clause_id") == clause:
                    citations.append(Citation(
                        clause_id=clause,
                        source_file=doc.metadata.get("source_file", "unknown"),
                        relevant_text=doc.content[:150] + "...",
                        domain=doc.metadata.get("domain", "unknown")
                    ))
                    break
        return citations
